FROM ruby:3.0.0-alpine

# dependencies
RUN apk add --no-cache \
  git build-base postgresql-dev \
  nodejs npm tzdata

# install recent yarn
RUN npm install -g yarn

# install bundler
RUN gem install bundler

# config home environment
WORKDIR /app

COPY Gemfile Gemfile.lock /app/
COPY vendor/bundle /app/vendor/bundle

ENV BUNDLE_CACHE_PATH "vendor/bundle"
ENV BUNDLE_PATH "vendor/bundle"
ENV BUNDLE_CACHE_ALL "true"
ENV BUNDLE_AUTO_INSTALL "false"

RUN bundle install --local
