name: CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup cache
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          key: 26790c8bfb947af3477f4729df178272d825f4e6


      - name: check files
        run: ls vendor

      - name: start server
        run: docker-compose up -d

      - name: lint
        run: docker-compose exec -T boilerplate_server bundle exec rubocop

      - name: test
        run: |
          docker-compose exec -T boilerplate_server bundle exec rspec
